artifact_uri: file:///Users/henrytomlinson/freqai_optimization/mlflow_tracking/170843114565167587/4ca5e383a3af4b91ba2fa7b271d0940c/artifacts
end_time: 1740816239693
entry_point_name: ''
experiment_id: '170843114565167587'
lifecycle_stage: active
run_id: 4ca5e383a3af4b91ba2fa7b271d0940c
run_name: legendary-perch-8
run_uuid: 4ca5e383a3af4b91ba2fa7b271d0940c
source_name: ''
source_type: 4
source_version: ''
start_time: 1740816239685
status: 3
tags: []
user_id: henrytomlinson
