artifact_uri: file:///Users/henrytomlinson/freqai_optimization/mlflow_tracking/170843114565167587/c45ae9dba7ce420f8496ceb5cec69473/artifacts
end_time: 1740819734241
entry_point_name: ''
experiment_id: '170843114565167587'
lifecycle_stage: active
run_id: c45ae9dba7ce420f8496ceb5cec69473
run_name: aged-crow-956
run_uuid: c45ae9dba7ce420f8496ceb5cec69473
source_name: ''
source_type: 4
source_version: ''
start_time: 1740819733575
status: 3
tags: []
user_id: henrytomlinson
