artifact_uri: file:///Users/henrytomlinson/freqai_optimization/mlflow_tracking/170843114565167587/a04c5eef136f4eaaba3080fdb33e146c/artifacts
end_time: 1740816240733
entry_point_name: ''
experiment_id: '170843114565167587'
lifecycle_stage: active
run_id: a04c5eef136f4eaaba3080fdb33e146c
run_name: righteous-fish-399
run_uuid: a04c5eef136f4eaaba3080fdb33e146c
source_name: ''
source_type: 4
source_version: ''
start_time: 1740816240722
status: 3
tags: []
user_id: henrytomlinson
