artifact_uri: file:///Users/henrytomlinson/freqai_optimization/mlflow_tracking/170843114565167587/addac729da5c40c4ac4595f6807f2a0f/artifacts
end_time: 1740819752516
entry_point_name: ''
experiment_id: '170843114565167587'
lifecycle_stage: active
run_id: addac729da5c40c4ac4595f6807f2a0f
run_name: calm-goat-606
run_uuid: addac729da5c40c4ac4595f6807f2a0f
source_name: ''
source_type: 4
source_version: ''
start_time: 1740819751793
status: 3
tags: []
user_id: henrytomlinson
