artifact_location: file:///Users/henrytomlinson/freqai_optimization/mlflow_tracking/170843114565167587
creation_time: 1740816239528
experiment_id: '170843114565167587'
last_update_time: 1740816239528
lifecycle_stage: active
name: FreqAI Optimization
