artifact_uri: file:///Users/henrytomlinson/freqai_optimization/mlflow_tracking/170843114565167587/a0ca36fc7d734ca8aefc9463ead40822/artifacts
end_time: 1740816240578
entry_point_name: ''
experiment_id: '170843114565167587'
lifecycle_stage: active
run_id: a0ca36fc7d734ca8aefc9463ead40822
run_name: persistent-ape-186
run_uuid: a0ca36fc7d734ca8aefc9463ead40822
source_name: ''
source_type: 4
source_version: ''
start_time: 1740816240568
status: 3
tags: []
user_id: henrytomlinson
