artifact_uri: file:///Users/henrytomlinson/freqai_optimization/mlflow_tracking/170843114565167587/3fedc4922fc54c8ca1818ce3db274cf7/artifacts
end_time: 1740816239783
entry_point_name: ''
experiment_id: '170843114565167587'
lifecycle_stage: active
run_id: 3fedc4922fc54c8ca1818ce3db274cf7
run_name: chill-stork-638
run_uuid: 3fedc4922fc54c8ca1818ce3db274cf7
source_name: ''
source_type: 4
source_version: ''
start_time: 1740816239765
status: 3
tags: []
user_id: henrytomlinson
