artifact_uri: file:///Users/henrytomlinson/freqai_optimization/mlflow_tracking/170843114565167587/d1ef95b9ad894908bb5ebdda2f56cc5e/artifacts
end_time: 1740816240461
entry_point_name: ''
experiment_id: '170843114565167587'
lifecycle_stage: active
run_id: d1ef95b9ad894908bb5ebdda2f56cc5e
run_name: stately-mole-587
run_uuid: d1ef95b9ad894908bb5ebdda2f56cc5e
source_name: ''
source_type: 4
source_version: ''
start_time: 1740816240452
status: 3
tags: []
user_id: henrytomlinson
