artifact_uri: file:///Users/henrytomlinson/freqai_optimization/mlflow_tracking/170843114565167587/fcabcce2cb154addad42a997e050f054/artifacts
end_time: 1740816239993
entry_point_name: ''
experiment_id: '170843114565167587'
lifecycle_stage: active
run_id: fcabcce2cb154addad42a997e050f054
run_name: resilient-stoat-206
run_uuid: fcabcce2cb154addad42a997e050f054
source_name: ''
source_type: 4
source_version: ''
start_time: 1740816239985
status: 3
tags: []
user_id: henrytomlinson
