artifact_uri: file:///Users/henrytomlinson/freqai_optimization/mlflow_tracking/170843114565167587/ea8c4da6bc4247b1803a361b0bfee4c5/artifacts
end_time: 1740819744220
entry_point_name: ''
experiment_id: '170843114565167587'
lifecycle_stage: active
run_id: ea8c4da6bc4247b1803a361b0bfee4c5
run_name: powerful-squid-659
run_uuid: ea8c4da6bc4247b1803a361b0bfee4c5
source_name: ''
source_type: 4
source_version: ''
start_time: 1740819743687
status: 3
tags: []
user_id: henrytomlinson
