artifact_uri: file:///Users/henrytomlinson/freqai_optimization/mlflow_tracking/170843114565167587/90c0b62bec5e4f83be532b0b783bf4ef/artifacts
end_time: 1740819776235
entry_point_name: ''
experiment_id: '170843114565167587'
lifecycle_stage: active
run_id: 90c0b62bec5e4f83be532b0b783bf4ef
run_name: amusing-skink-96
run_uuid: 90c0b62bec5e4f83be532b0b783bf4ef
source_name: ''
source_type: 4
source_version: ''
start_time: 1740819775571
status: 3
tags: []
user_id: henrytomlinson
