artifact_uri: file:///Users/henrytomlinson/freqai_optimization/mlflow_tracking/170843114565167587/34f780a4be7a4198b61af4cceaaea52f/artifacts
end_time: 1740816240291
entry_point_name: ''
experiment_id: '170843114565167587'
lifecycle_stage: active
run_id: 34f780a4be7a4198b61af4cceaaea52f
run_name: fun-ram-470
run_uuid: 34f780a4be7a4198b61af4cceaaea52f
source_name: ''
source_type: 4
source_version: ''
start_time: 1740816240281
status: 3
tags: []
user_id: henrytomlinson
