artifact_uri: file:///Users/henrytomlinson/freqai_optimization/mlflow_tracking/170843114565167587/a2f63d0de1dc446584ecca63b71bbece/artifacts
end_time: 1740816239625
entry_point_name: ''
experiment_id: '170843114565167587'
lifecycle_stage: active
run_id: a2f63d0de1dc446584ecca63b71bbece
run_name: valuable-midge-477
run_uuid: a2f63d0de1dc446584ecca63b71bbece
source_name: ''
source_type: 4
source_version: ''
start_time: 1740816239619
status: 3
tags: []
user_id: henrytomlinson
