artifact_uri: file:///Users/henrytomlinson/freqai_optimization/mlflow_tracking/170843114565167587/64acee0d93e549ebaec79aa8ed50cf28/artifacts
end_time: 1740819748156
entry_point_name: ''
experiment_id: '170843114565167587'
lifecycle_stage: active
run_id: 64acee0d93e549ebaec79aa8ed50cf28
run_name: indecisive-tern-472
run_uuid: 64acee0d93e549ebaec79aa8ed50cf28
source_name: ''
source_type: 4
source_version: ''
start_time: 1740819747422
status: 3
tags: []
user_id: henrytomlinson
