artifact_uri: file:///Users/henrytomlinson/freqai_optimization/mlflow_tracking/170843114565167587/ee7e8ed06ef040148efbeab5f3cb31d8/artifacts
end_time: 1740816240618
entry_point_name: ''
experiment_id: '170843114565167587'
lifecycle_stage: active
run_id: ee7e8ed06ef040148efbeab5f3cb31d8
run_name: righteous-hen-258
run_uuid: ee7e8ed06ef040148efbeab5f3cb31d8
source_name: ''
source_type: 4
source_version: ''
start_time: 1740816240604
status: 3
tags: []
user_id: henrytomlinson
