artifact_uri: file:///Users/henrytomlinson/freqai_optimization/mlflow_tracking/170843114565167587/e9521fc5ac1b4b899db6ed336bdd9c6f/artifacts
end_time: 1740816240095
entry_point_name: ''
experiment_id: '170843114565167587'
lifecycle_stage: active
run_id: e9521fc5ac1b4b899db6ed336bdd9c6f
run_name: mercurial-loon-798
run_uuid: e9521fc5ac1b4b899db6ed336bdd9c6f
source_name: ''
source_type: 4
source_version: ''
start_time: 1740816240086
status: 3
tags: []
user_id: henrytomlinson
