artifact_uri: file:///Users/henrytomlinson/freqai_optimization/mlflow_tracking/170843114565167587/b7385a1ab52b4dc3a06ef4c2c7f8b2b6/artifacts
end_time: 1740816240660
entry_point_name: ''
experiment_id: '170843114565167587'
lifecycle_stage: active
run_id: b7385a1ab52b4dc3a06ef4c2c7f8b2b6
run_name: hilarious-sow-89
run_uuid: b7385a1ab52b4dc3a06ef4c2c7f8b2b6
source_name: ''
source_type: 4
source_version: ''
start_time: 1740816240649
status: 3
tags: []
user_id: henrytomlinson
